In [9]:
import numpy as np

# For a matrix, each inner list is one row.
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 3], [2, 4]])
print("A =\n", A)
print("B =\n", B)

# Column vectors are often written as matrices with one column.
a = np.array([[1], [2], [3]])
b = np.array([[4], [5]])
print("a =\n", a)
print("b =\n", b)

print("A.shape =", A.shape)
print("a.shape =", a.shape)

A =
 [[1 2]
 [3 4]]
B =
 [[1 3]
 [2 4]]
a =
 [[1]
 [2]
 [3]]
b =
 [[4]
 [5]]
A.shape = (2, 2)
a.shape = (3, 1)


In [11]:
A = np.array([[1, 2], [3, 4]])
A_T = A.T
print("A =\n", A)
print("A.T =\n", A_T)

a = np.array([[1], [2], [3]])
a_T = a.T
print("a =\n", a)
print("a.T =\n", a_T)

A =
 [[1 2]
 [3 4]]
A.T =
 [[1 3]
 [2 4]]
a =
 [[1]
 [2]
 [3]]
a.T =
 [[1 2 3]]


In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

# Dot product = multiply corresponding elements and add.
# 1*4 + 2*5 + 3*6 = 32
by_hand = 1 * 4 + 2 * 5 + 3 * 6

print("by hand:", by_hand)
print("np.dot(a.T, b):\n", np.dot(a.T, b))
print("a.T.dot(b):\n", a.T.dot(b))
print("a.T @ b:\n", a.T @ b)

# For 1D arrays, NumPy returns a scalar-like value instead of a 1x1 matrix.
# a_1d = np.array([1, 2, 3])
# b_1d = np.array([4, 5, 6])
# print("a_1d @ b_1d:", a_1d @ b_1d)
# print("a_1d @ b_1d:", np.dot(a_1d, b_1d))

by hand: 32


ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A =\n", A)
print("B =\n", B)
print("A @ B =\n", A @ B)

# Dimension mismatch example.
C = np.array([[1, 2, 3], [4, 5, 6]])  # shape 2 x 3
D = np.array([[1, 2], [3, 4]])        # shape 2 x 2
print("C.shape =", C.shape)
print("D.shape =", D.shape)
try:
    print(C @ D)
except ValueError as e:
    print("C @ D gives an error because the inner dimensions do not match:")
#     print(e)

A =
 [[1 2]
 [3 4]]
B =
 [[5 6]
 [7 8]]
A @ B =
 [[19 22]
 [43 50]]
C.shape = (2, 3)
D.shape = (2, 2)
C @ D gives an error because the inner dimensions do not match:


In [22]:
A = np.array([[1, 2], [3, 4]])
I2 = np.eye(2)
I3 = np.eye(3)

print("2x2 identity matrix:\n", I2)
print("3x3 identity matrix:\n", I3)
print("A @ I2 =\n", A @ I2)
print("I2 @ A =\n", I2 @ A)

2x2 identity matrix:
 [[1. 0.]
 [0. 1.]]
3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A @ I2 =
 [[1. 2.]
 [3. 4.]]
I2 @ A =
 [[1. 2.]
 [3. 4.]]


In [23]:
A = np.array([[1, 2], [3, 4]])
Ainv = np.linalg.inv(A)

print("A =\n", A)
print("A inverse =\n", Ainv)
print("A @ Ainv =\n", A @ Ainv)
print("Ainv @ A =\n", Ainv @ A)
print("Close to identity?", np.allclose(A @ Ainv, np.eye(2)))

# # Not every matrix has an inverse.
# singular = np.array([[1, 2], [2, 4]])
# non_square = np.array([[1, 2], [3, 4], [5, 6]])
# print("\nSingular matrix =\n", singular)
# print("\nNon-square matrix =\n", non_square)

# try:
#     np.linalg.inv(singular)
#     # np.linalg.inv(non_square)
# except np.linalg.LinAlgError as e:
#     print("Cannot invert this matrix:", e)

A =
 [[1 2]
 [3 4]]
A inverse =
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ Ainv =
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Ainv @ A =
 [[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]
Close to identity? True


In [24]:
import numpy as np

# Make matrices
a = np.array([[1], [2]])
b = np.array([[5], [6]])
A = np.array([[1, 3], [2, 4]])
B = np.array([[5, 7], [6, 8]])