In [ ]:
# Programming exercise: vectors, matrices, products, inverses

import numpy as np

# Make matrices
a = np.array([[1], [2]])
b = np.array([[5], [6]])
A = np.array([[1, 3], [2, 4]])
B = np.array([[5, 7], [6, 8]])

print("a =\n", a)
print("b =\n", b)
print("A =\n", A)
print("B =\n", B)

# Dot products. Because a and b are column vectors, transpose the first one.
print("1. a dot b =\n", a.T @ b, np.dot(a.T, b), a.T.dot(b))
print("2. b dot a =\n", b.T @ a)

# Matrix-vector products.
print("3. A @ a =\n", A @ a)
print("4. B @ b =\n", B @ b)


# Matrix-matrix products.
print("5. A @ B =\n", A @ B)
print("6. B @ A =\n", B @ A)

# Inverses.
Ainv = np.linalg.inv(A)
Binv = np.linalg.inv(B)
print("7. inverse of A =\n", Ainv)
print("   A @ Ainv =\n", A @ Ainv)
print("8. inverse of B =\n", Binv)
print("   B @ Binv =\n", B @ Binv)

a =
 [[1]
 [2]]
b =
 [[5]
 [6]]
A =
 [[1 3]
 [2 4]]
B =
 [[5 7]
 [6 8]]
1. a dot b =
 [[17]] [[17]] [[17]]
2. b dot a =
 [[17]]
3. A @ a =
 [[ 7]
 [10]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)